use ipnet::IpNet;
use serde::Deserialize;
use std::net::SocketAddr;
use std::path::PathBuf;

#[derive(Debug, Clone, Deserialize)]
pub struct Config {
    pub server: ServerConfig,
    pub storage: StorageConfig,
    pub network: NetworkConfig,
    #[serde(default)]
    pub logging: LoggingConfig,
    #[serde(default)]
    pub update_check: UpdateCheckConfig,
    #[serde(default)]
    pub mcp: McpConfig,
}

#[derive(Debug, Clone, Deserialize)]
pub struct ServerConfig {
    pub bind_addr: SocketAddr,
    /// Required. Use `pkvsyncd genkey` to generate.
    pub deployment_key: String,
    /// Optional. If set, used to construct shareable URLs.
    #[serde(default)]
    pub public_host: Option<String>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct StorageConfig {
    pub data_dir: PathBuf,
    pub db_path: PathBuf,
}

#[derive(Debug, Clone, Deserialize)]
pub struct NetworkConfig {
    /// IPs/CIDRs whose `X-Forwarded-For` we trust.
    pub trusted_proxies: Vec<IpNet>,
}

#[derive(Debug, Clone, Deserialize)]
pub struct LoggingConfig {
    #[serde(default = "default_log_level")]
    pub level: String,
    #[serde(default)]
    pub format: LoggingFormat,
}

#[derive(Debug, Clone, Deserialize)]
pub struct UpdateCheckConfig {
    #[serde(default = "default_update_check_enabled")]
    pub enabled: bool,
    #[serde(default = "default_update_check_interval_seconds")]
    pub interval_seconds: u64,
    #[serde(default = "default_update_check_repo")]
    pub repo: String,
}

#[derive(Debug, Clone, Deserialize, Default)]
pub struct McpConfig {
    #[serde(default)]
    pub embed_in_serve: bool,
}

#[derive(Debug, Default, Clone, Copy, PartialEq, Eq)]
pub enum LoggingFormat {
    #[default]
    Json,
    Pretty,
}

impl Default for LoggingConfig {
    fn default() -> Self {
        Self {
            level: default_log_level(),
            format: LoggingFormat::Json,
        }
    }
}

fn default_log_level() -> String {
    "info".to_string()
}

impl Default for UpdateCheckConfig {
    fn default() -> Self {
        Self {
            enabled: default_update_check_enabled(),
            interval_seconds: default_update_check_interval_seconds(),
            repo: default_update_check_repo(),
        }
    }
}

fn default_update_check_enabled() -> bool {
    true
}

fn default_update_check_interval_seconds() -> u64 {
    86_400
}

fn default_update_check_repo() -> String {
    "cyberkurry/pkv-sync".to_string()
}

impl<'de> Deserialize<'de> for LoggingFormat {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = String::deserialize(deserializer)?;
        match value.as_str() {
            "json" => Ok(Self::Json),
            "pretty" => Ok(Self::Pretty),
            _ => Err(serde::de::Error::custom(format!(
                "unknown logging format '{value}', expected 'json' or 'pretty'"
            ))),
        }
    }
}

impl Config {
    pub fn load(path: &std::path::Path) -> Result<Self, ConfigError> {
        let raw =
            std::fs::read_to_string(path).map_err(|e| ConfigError::Read(path.to_path_buf(), e))?;
        let cfg: Self = toml::from_str(&raw).map_err(ConfigError::Parse)?;
        cfg.validate()?;
        Ok(cfg)
    }

    fn validate(&self) -> Result<(), ConfigError> {
        if !valid_deployment_key(&self.server.deployment_key) {
            return Err(ConfigError::Invalid(
                "deployment_key must be generated by `pkvsyncd genkey` (`k_` plus 32 lowercase hex characters)"
                    .into(),
            ));
        }
        if !valid_update_check_repo(&self.update_check.repo) {
            return Err(ConfigError::Invalid(
                "update_check.repo must be in owner/repo format using ASCII letters, digits, '.', '_', or '-'"
                    .into(),
            ));
        }
        Ok(())
    }
}

fn valid_deployment_key(key: &str) -> bool {
    key.len() == 34
        && key.starts_with("k_")
        && key[2..]
            .bytes()
            .all(|b| b.is_ascii_digit() || (b'a'..=b'f').contains(&b))
}

fn valid_update_check_repo(repo: &str) -> bool {
    let Some((owner, name)) = repo.split_once('/') else {
        return false;
    };
    if owner.is_empty() || name.is_empty() || name.contains('/') || repo.trim() != repo {
        return false;
    }
    owner
        .bytes()
        .all(|b| b.is_ascii_alphanumeric() || b == b'_' || b == b'-')
        && name
            .bytes()
            .all(|b| b.is_ascii_alphanumeric() || b == b'_' || b == b'-' || b == b'.')
}

#[derive(Debug, thiserror::Error)]
pub enum ConfigError {
    #[error("reading config file {0}: {1}")]
    Read(PathBuf, std::io::Error),
    #[error("parsing config: {0}")]
    Parse(#[from] toml::de::Error),
    #[error("invalid config: {0}")]
    Invalid(String),
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;

    const VALID_DEPLOYMENT_KEY: &str = "k_0123456789abcdef0123456789abcdef";

    fn write_temp(content: &str) -> tempfile::NamedTempFile {
        let mut f = tempfile::NamedTempFile::new().unwrap();
        f.write_all(content.as_bytes()).unwrap();
        f
    }

    #[test]
    fn loads_minimal_valid_config() {
        let f = write_temp(
            r#"
            [server]
            bind_addr = "127.0.0.1:6710"
            deployment_key = "k_0123456789abcdef0123456789abcdef"

            [storage]
            data_dir = "/var/lib/pkv-sync"
            db_path = "/var/lib/pkv-sync/metadata.db"

            [network]
            trusted_proxies = ["127.0.0.1/32", "::1/128"]
            "#,
        );
        let cfg = Config::load(f.path()).expect("config loads");
        assert_eq!(cfg.server.bind_addr.port(), 6710);
        assert_eq!(cfg.server.deployment_key, VALID_DEPLOYMENT_KEY);
        assert_eq!(cfg.network.trusted_proxies.len(), 2);
        assert_eq!(cfg.logging.level, "info");
        assert_eq!(cfg.logging.format, LoggingFormat::Json);
    }

    #[test]
    fn loads_pretty_logging_format() {
        let f = write_temp(
            r#"
            [server]
            bind_addr = "127.0.0.1:6710"
            deployment_key = "k_0123456789abcdef0123456789abcdef"

            [storage]
            data_dir = "/x"
            db_path = "/x/y"

            [network]
            trusted_proxies = []

            [logging]
            level = "debug"
            format = "pretty"
            "#,
        );
        let cfg = Config::load(f.path()).expect("config loads");
        assert_eq!(cfg.logging.level, "debug");
        assert_eq!(cfg.logging.format, LoggingFormat::Pretty);
    }

    #[test]
    fn rejects_unknown_logging_format() {
        let f = write_temp(
            r#"
            [server]
            bind_addr = "127.0.0.1:6710"
            deployment_key = "k_0123456789abcdef0123456789abcdef"

            [storage]
            data_dir = "/x"
            db_path = "/x/y"

            [network]
            trusted_proxies = []

            [logging]
            format = "xml"
            "#,
        );
        let err = Config::load(f.path()).unwrap_err();
        assert!(
            err.to_string().to_lowercase().contains("logging format"),
            "expected logging format parse error, got: {err}"
        );
    }

    #[test]
    fn reports_missing_required_field() {
        let f = write_temp(
            r#"
            [server]
            bind_addr = "127.0.0.1:6710"

            [storage]
            data_dir = "/x"
            db_path = "/x/y"

            [network]
            trusted_proxies = []
            "#,
        );
        let err = Config::load(f.path()).unwrap_err();
        assert!(
            err.to_string().to_lowercase().contains("deployment_key"),
            "expected 'deployment_key' missing error, got: {err}"
        );
    }

    #[test]
    fn rejects_weak_deployment_key() {
        let f = write_temp(
            r#"
            [server]
            bind_addr = "127.0.0.1:6710"
            deployment_key = "k_test"

            [storage]
            data_dir = "/x"
            db_path = "/x/y"

            [network]
            trusted_proxies = []
            "#,
        );
        let err = Config::load(f.path()).unwrap_err();
        assert!(
            err.to_string().contains("deployment_key"),
            "expected deployment_key validation error, got: {err}"
        );
    }

    #[test]
    fn reports_io_error_for_missing_file() {
        let err = Config::load(std::path::Path::new("/nonexistent/path/x.toml")).unwrap_err();
        assert!(matches!(err, ConfigError::Read(_, _)));
    }

    #[test]
    fn loads_optional_public_host() {
        let f = write_temp(
            r#"
            [server]
            bind_addr = "127.0.0.1:6710"
            deployment_key = "k_0123456789abcdef0123456789abcdef"
            public_host = "sync.example.com"

            [storage]
            data_dir = "/x"
            db_path = "/x/y"

            [network]
            trusted_proxies = []
            "#,
        );
        let cfg = Config::load(f.path()).unwrap();
        assert_eq!(cfg.server.public_host.as_deref(), Some("sync.example.com"));
    }

    #[test]
    fn update_check_defaults_to_daily_github_release_checks() {
        let f = write_temp(
            r#"
            [server]
            bind_addr = "127.0.0.1:6710"
            deployment_key = "k_0123456789abcdef0123456789abcdef"

            [storage]
            data_dir = "/x"
            db_path = "/x/y"

            [network]
            trusted_proxies = []
            "#,
        );
        let cfg = Config::load(f.path()).unwrap();
        assert!(cfg.update_check.enabled);
        assert_eq!(cfg.update_check.interval_seconds, 86_400);
        assert_eq!(cfg.update_check.repo, "cyberkurry/pkv-sync");
    }

    #[test]
    fn update_check_can_be_disabled_for_air_gapped_deployments() {
        let f = write_temp(
            r#"
            [server]
            bind_addr = "127.0.0.1:6710"
            deployment_key = "k_0123456789abcdef0123456789abcdef"

            [storage]
            data_dir = "/x"
            db_path = "/x/y"

            [network]
            trusted_proxies = []

            [update_check]
            enabled = false
            interval_seconds = 172800
            repo = "example/fork"
            "#,
        );
        let cfg = Config::load(f.path()).unwrap();
        assert!(!cfg.update_check.enabled);
        assert_eq!(cfg.update_check.interval_seconds, 172_800);
        assert_eq!(cfg.update_check.repo, "example/fork");
    }

    #[test]
    fn rejects_invalid_update_check_repo_format() {
        let f = write_temp(
            r#"
            [server]
            bind_addr = "127.0.0.1:6710"
            deployment_key = "k_0123456789abcdef0123456789abcdef"

            [storage]
            data_dir = "/x"
            db_path = "/x/y"

            [network]
            trusted_proxies = []

            [update_check]
            repo = "https://example.com/cyberkurry/pkv-sync"
            "#,
        );
        let err = Config::load(f.path()).unwrap_err();
        assert!(
            err.to_string().contains("update_check.repo"),
            "expected update_check.repo validation error, got: {err}"
        );
    }

    #[test]
    fn config_defaults_mcp_embed_to_false_when_section_absent() {
        let f = write_temp(
            r#"
            [server]
            bind_addr = "127.0.0.1:6710"
            deployment_key = "k_0123456789abcdef0123456789abcdef"

            [storage]
            data_dir = "/x"
            db_path = "/x/y"

            [network]
            trusted_proxies = []
            "#,
        );
        let cfg = Config::load(f.path()).unwrap();
        assert!(!cfg.mcp.embed_in_serve);
    }

    #[test]
    fn config_accepts_mcp_embed_true() {
        let f = write_temp(
            r#"
            [server]
            bind_addr = "127.0.0.1:6710"
            deployment_key = "k_0123456789abcdef0123456789abcdef"

            [storage]
            data_dir = "/x"
            db_path = "/x/y"

            [network]
            trusted_proxies = []

            [mcp]
            embed_in_serve = true
            "#,
        );
        let cfg = Config::load(f.path()).unwrap();
        assert!(cfg.mcp.embed_in_serve);
    }

    #[test]
    fn config_types_do_not_keep_unused_serialization_helpers() {
        let source = include_str!("config.rs");
        let serialize_ident = concat!("Serial", "ize");
        let as_str_method = concat!("pub fn as", "_str");

        assert!(!source.contains(serialize_ident));
        assert!(!source.contains(as_str_method));
    }
}
